name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.idea/..'
      - 'docs/**'

jobs:
  build:
    name: Build x86_64
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Run build script
      run: ./scripts/build.sh -a amd64 appimagetool
    - name: Upload to GitHub Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ./build/*
